### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cnsquare** [yottabit42/gtakeout_backup#1]
It looks like Google fixed this loophole.

The URL copied does not include the extra detail your URL shows in the video. <https://www.youtube.com/watch?v=h5idAEJorIc&ab_channel=JacobMcDonald>

![image](https://github.com/user-attachments/assets/0b8d032f-6eb3-4f6d-b6df-dfc2d3b26f47)

https://takeout-download.usercontent.google.com/download/takeout-20240927T123023Z-001.tgz?j=5a2bb86c-bfd6-4941-905c-8f393440d020&i=19&user=6690d14952514&authuser=0

This is the result
1.tgz                         [ <=>                                     ] 449.04K  --.-KB/s    in 0.04s
2.tgz                         [ <=>                                     ] 449.04K  --.-KB/s    in 0.04s

**Comment by yottabit42** [comment]
Well that's disappointing! I'll investigate. Did you inspect the download to see if it's just text with an error message?

**Comment by yottabit42** [comment]
Hey I have a working solution again. I'll rewrite my script shortly and redo the video.

We now have to select 'copy as cURL' and use curl instead of wget:
`curl <cURL_paste> --output <filename>`

**Comment by cnsquare** [comment]
Excellent! I'm looking forward to testing it.

Below is my workaround. I hope it helps.
curl --remote-name --remote-header-name --location  '<copy as cURL (bash)>' &

![image](https://github.com/user-attachments/assets/463b4f21-9507-4d8f-a90f-305db911809e)
