### ISSUE TITLE
Only 1 Transfer

### ISSUE THREAD

**Issue by seffyroff** [yottabit42/gtakeout_backup#4]
Hey there, thanks for making and sharing this!

I added 10 takeout urls to the script prompt, then pressed enter.  It's only showing 1 active xfer for some reason.  Was I too slow?

EDIT: I Don't think I was too slow, as it's currently transferring the first cURL.

EDIT2: At the end of the first transfer, it exited.  It did download it successfully though.

**Comment by yottabit42** [comment]
Hello! After running the script, you will paste the first cURL into the prompt, and then press Enter. Next paste the second cURL and press Enter, etc. Keep going until you have added as many as you want. Pressing Enter at the prompt without a cURL pasted first will start the downloads.

I am currently downloading 8 in parallel now:
```
Paste cURL, then press Enter, or Enter alone to end: 
DL% UL%  Dled  Uled  Xfers  Live Total     Current  Left    Speed
  4 --  16.3G     0     8     8   1:01:37  0:02:32  0:59:06  110M
```
